config/routes.rb
Rails.application.routes.draw do
	root "timeline#show"
	
	resource :timeline, only: [:show], controller: 'timeline'
  resource :session, only: [:new, :create, :destroy]

	resources :friends
	
  resources :users do
    member do
      post 'add_as_friend'
    end
  end
  
end

app/models/friend.rb
class Friend < ActiveRecord::Base
  belongs_to :user
  belongs_to :friend, class_name: 'User'
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :friends

  def friends_with(user)

    user.friends.where(friend_id: id).any?
    
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  
  protect_from_forgery with: :exception

  def current_user
    @user ||= User.find_by(id: session[:user_id])
  end
  
  helper_method :current_user

  def require_signed_in!
    unless current_user.present?
      redirect_to new_session_path, notice: 'You must be signed in'
    end
  end
  
end

app/controllers/friends_controller.rb
class FriendsController < ApplicationController
  before_filter :require_signed_in!

  def index
    friend_ids = current_user.friends.pluck(:friend_id)
    @friends = User.find(friend_ids).sort_by(&:name)
  end
  
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find(params[:user_id])
    session[:user_id] = user.id
    redirect_to root_path, notice: "Signed in as #{user.name}"
  end

  def destroy
    reset_session
    redirect_to root_path, notice: "You signed out"
  end

end

app/controllers/timeline_controller.rb
class TimelineController < ApplicationController

  def show
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :require_signed_in!

  def index
  end

  def add_as_friend
    friend = User.find(params[:id])
    Friend.create!(user_id: current_user.id, friend_id: friend.id)
    redirect_to friends_path, notice: "Added #{friend.name} as a friend"
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/friends/index.html.erb
<div class="row">
  <div class="col-lg-6">
    <h1>Friends</h1>
    <% if @friends.any? %>
      <ul>
        <% for friend in @friends %>
          <li>
            <%= friend.name %>
          </li>
        <% end %>
      </ul>
    <% else %>
      <p><strong>No Friends!!</strong></p>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Friendbook</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <div class="container">
          <div class="header">
            <nav>
              <ul class="nav nav-pills pull-right">
                <li role="presentation">
                  <%= link_to "Timeline", timeline_path %>
                </li>
                <li role="presentation">
                  <%= link_to "Users", users_path %>
                </li>
                <li role="presentation">
                  <%= link_to "Friends", friends_path %>
                </li>
                <li role="presentation" class="active">
                  <% if current_user.present? %>
                    <%= link_to current_user.name, session_path, data:{confirm: 'Sign Out?'}, method: "DELETE" %>
                  <% else %>
                    <%= link_to "Sign In", new_session_path %>
                  <% end %>
                </li>
              </ul>
            </nav>
            <h3 class="text-muted">
              <%= link_to "Friendbook", root_path %>
            </h3>
          </div>
          <% if flash[:notice] %>
            <div class="alert alert-info" role="alert">
              <%= flash[:notice] %>
            </div>
          <% end %>

          <%= yield %>

          <footer class="footer">
            <p>&copy; Friendbook 
            	<script type="text/javascript">
								//<![CDATA[
								var d = new Date()
								document.write(d.getFullYear())
								//]]>
							</script>
						</p>
          </footer>

        </div> <!-- /container -->
  </body>
</html>

app/views/timeline/show.html.erb
<div class="jumbotron">
   <h1>Timeline</h1>
   <p class="lead">Cras justo odio, dapibus ac facilisis in, egestas eget quam. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus.</p>
   <p><a class="btn btn-lg btn-success" href="#" role="button">Sign up today</a></p>
</div>

app/views/users/index.html.erb
<div class="row">
  <div class="col-lg-6">
    <h1>Users</h1>
    <% if User.any? %>
      <ul>
        <% for user in User.order(:name) %>
          <li style="padding: 10px 0">
            <%= user.name %>
            <% unless user.friends_with(current_user) %>
              <%= button_to 'Add as friend', add_as_friend_user_path(user), class: 'btn btn-sm btn-default' %>
            <% end %>
          </li>
        <% end %>
      </ul>
    <% else %>
      <p><strong>No Users!!</strong></p>
    <% end %>
  </div>
</div>